In [1]:
#Creating Data

In [2]:
import pandas as pd
import numpy as np

In [10]:
current_price = np.array([np.random.randint(0,101) for i in np.arange(0,100)])
current_price

array([36, 45, 32, 13, 85, 27, 81, 79, 42,  0, 69,  6, 25, 90, 42, 55, 51,
       13,  6, 77, 63, 89, 59, 71, 84, 96, 29, 72, 36, 19, 13, 22, 70, 29,
       42, 52, 31, 70, 59, 67, 62, 94, 24,  2, 72, 83,  4, 26, 84,  8,  6,
       15, 92, 45, 67, 78, 27, 67, 36,  5, 71, 92, 19, 35, 37,  2, 82, 65,
       11, 50, 39, 28, 25, 63, 94, 15, 51, 14, 99, 42, 54, 35,  8, 53, 42,
       78, 55, 78, 79, 85, 37, 77, 17, 97, 20, 76, 31, 74, 11,  8])

In [9]:
one_week_movement = np.array([np.random.randint(-5,6) for i in np.arange(0,100)])
one_week_movement

array([ 3, -2, -4, -2, -4,  2, -1, -2,  2,  0,  0, -5, -4,  1,  0,  0,  5,
        1, -2,  4,  5, -3, -4, -1, -3, -5, -1, -3,  4, -5,  1,  4,  5,  0,
       -2,  3,  4, -4, -3,  5,  2,  4,  1,  4, -5, -3,  1, -5, -2, -3,  3,
       -2, -3,  5,  3,  1,  4,  5, -4,  2, -4,  0, -4, -3,  2, -2,  0, -5,
       -5, -4,  1, -3, -5,  0,  1,  4,  0, -1,  0, -2,  4,  1,  5,  2,  3,
       -2,  0,  0,  5, -1, -5,  1, -3, -2, -5, -5,  3, -3,  4,  3])

In [8]:
in_the_news = np.array([np.random.randint(0,2) for i in np.arange(0,100)])
in_the_news

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1])

In [13]:
sentiment_twitter = np.array([np.random.randint(0,3) for i in np.arange(0,100)])
sentiment_twitter

array([1, 2, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 2, 1, 2, 1, 0, 2, 2, 1, 1,
       2, 1, 0, 1, 1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 0, 1, 0, 1, 1, 0, 0, 2, 2,
       1, 2, 1, 2, 2, 1, 2, 1, 2, 0, 1, 2, 2, 2, 0, 0, 2, 0, 0, 1, 0, 0, 0,
       0, 2, 1, 1, 1, 0, 1, 2, 2, 1, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 1, 0, 0,
       0, 2, 1, 2, 0, 1, 1, 1])

In [14]:
table_of_strategy = pd.DataFrame({ 'current_price' : current_price, 'one_week_movement' : one_week_movement,
                                  'news' : in_the_news, 'twitter': sentiment_twitter })
table_of_strategy

current_price  news  one_week_movement  twitter
0              36     0                  3        1
1              45     0                 -2        2
2              32     0                 -4        1
3              13     0                 -2        1
4              85     0                 -4        0
5              27     0                  2        1
6              81     0                 -1        0
7              79     0                 -2        1
8              42     0                  2        0
9               0     1                  0        0
10             69     0                  0        1
11              6     0                 -5        0
12             25     0                 -4        1
13             90     0                  1        1
14             42     1                  0        2
15             55     1                  0        1
16             51     0                  5        2
17             13     1                  1        1
18              6     0                 -2        0
19             77     0                  4        2
20             63     0                  5        2
21             89     0                 -3        1
22             59     1                 -4        1
23             71     1                 -1        2
24             84     1                 -3        1
25             96     0                 -5        0
26             29     1                 -1        1
27             72     0                 -3        1
28             36     1                  4        1
29             19     1                 -5        1
..            ...   ...                ...      ...
70             39     1                  1        2
71             28     0                 -3        1
72             25     1                 -5        1
73             63     0                  0        1
74             94     1                  1        0
75             15     0                  4        1
76             51     0                  0        2
77             14     0                 -1        2
78             99     1                  0        1
79             42     1                 -2        0
80             54     1                  4        1
81             35     1                  1        1
82              8     1                  5        2
83             53     0                  2        2
84             42     0                  3        1
85             78     0                 -2        0
86             55     0                  0        2
87             78     0                  0        1
88             79     1                  5        0
89             85     1                 -1        1
90             37     0                 -5        0
91             77     1                  1        0
92             17     1                 -3        0
93             97     0                 -2        2
94             20     0                 -5        1
95             76     0                 -5        2
96             31     1                  3        0
97             74     0                 -3        1
98             11     0                  4        1
99              8     1                  3        1

[100 rows x 4 columns]

In [24]:
# Keys assumed for the next bit
# Movement is in percentages 
# in_the_news: 0 is no, 1 is yes
# twitter: 0 is neg, 1 is pos, 2 is neutral/not significant
# 1 is move, 0 is stay

In [25]:
output_class = []

In [27]:
for index in np.arange(0, 100):
    if one_week_movement[index] >= 0:
        if sentiment_twitter[index] == 0:
            if in_the_news[index] == 0:
                output_class = output_class + [0]
#                 Gained, twitter hate, not in news - Uncertainity
            else:
                output_class = output_class + [0]
#                 Gained, twitter hate, in news - Mass Movement - Soft 1
        else:
            if in_the_news[index] == 0:
                output_class = output_class + [1]
#                Gained, twitter love, not in new - Move
            else:
                output_class = output_class + [0]
#             Gained, twitter love, in news - Mass Movement
    else:
        if sentiment_twitter[index] == 0:
            if in_the_news[index] == 0:
                output_class = output_class + [1]
#                 Lost, twitter hate, not in news - Move
            else:
                output_class = output_class + [0]
#             Lost, twitter hate, in news - Mass Movement
        else:
            if in_the_news[index] == 0:
                output_class = output_class + [0]
#                 Lost, twitter love, not in news - Uncertainity
            else:
                output_class = output_class + [1]
#             Lost, twitter love, in news - Mass Movement

In [30]:
out_class = np.array(output_class)
out_class

array([1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0])

In [31]:
table_of_strategy = pd.DataFrame({ 'current_price' : current_price, 'one_week_movement' : one_week_movement,
                                  'news' : in_the_news, 'twitter': sentiment_twitter, 'class': out_class })
table_of_strategy

class  current_price  news  one_week_movement  twitter
0       1             36     0                  3        1
1       0             45     0                 -2        2
2       0             32     0                 -4        1
3       0             13     0                 -2        1
4       1             85     0                 -4        0
5       1             27     0                  2        1
6       1             81     0                 -1        0
7       0             79     0                 -2        1
8       0             42     0                  2        0
9       0              0     1                  0        0
10      1             69     0                  0        1
11      1              6     0                 -5        0
12      0             25     0                 -4        1
13      1             90     0                  1        1
14      0             42     1                  0        2
15      0             55     1                  0        1
16      1             51     0                  5        2
17      0             13     1                  1        1
18      1              6     0                 -2        0
19      1             77     0                  4        2
20      1             63     0                  5        2
21      0             89     0                 -3        1
22      1             59     1                 -4        1
23      1             71     1                 -1        2
24      1             84     1                 -3        1
25      1             96     0                 -5        0
26      1             29     1                 -1        1
27      0             72     0                 -3        1
28      0             36     1                  4        1
29      1             19     1                 -5        1
..    ...            ...   ...                ...      ...
70      0             39     1                  1        2
71      0             28     0                 -3        1
72      1             25     1                 -5        1
73      1             63     0                  0        1
74      0             94     1                  1        0
75      1             15     0                  4        1
76      1             51     0                  0        2
77      0             14     0                 -1        2
78      0             99     1                  0        1
79      0             42     1                 -2        0
80      0             54     1                  4        1
81      0             35     1                  1        1
82      0              8     1                  5        2
83      1             53     0                  2        2
84      1             42     0                  3        1
85      1             78     0                 -2        0
86      1             55     0                  0        2
87      1             78     0                  0        1
88      0             79     1                  5        0
89      1             85     1                 -1        1
90      1             37     0                 -5        0
91      0             77     1                  1        0
92      0             17     1                 -3        0
93      0             97     0                 -2        2
94      0             20     0                 -5        1
95      0             76     0                 -5        2
96      0             31     1                  3        0
97      0             74     0                 -3        1
98      1             11     0                  4        1
99      0              8     1                  3        1

[100 rows x 5 columns]

In [34]:
table_of_strategy.to_csv('train_data_attempt2')